# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.synced_folder "../../", "/vagrant"

  # Kubernetes Master Server
  config.vm.define "master.k8s" do |node|
    node.vm.box = "ubuntu/focal64"
    node.vm.box_check_update = false
    node.vm.hostname = "master.k8s"
    node.vm.network "private_network", ip: "192.168.56.10"
    # node.vm.network "private_network", ip: "10.100.50.10"
  
    node.vm.provider "virtualbox" do |v|
      v.name = "master"
      v.memory = 4096
      v.cpus = 4
    end

    node.vm.provision "shell", path: "bootstrap_master.sh"
  end

  # Kubernetes Worker Nodes
  NodeCount = 1

  (1..NodeCount).each do |i|

    config.vm.define "node#{i}.k8s" do |node|
      node.vm.box = "ubuntu/focal64"
      node.vm.box_check_update = false
      node.vm.hostname = "node#{i}.k8s"
      node.vm.network "private_network", ip: "192.168.56.1#{i}"
      # node.vm.network "private_network", ip: "10.50.100.5#{i}"

      node.vm.provider "virtualbox" do |v|
        v.name = "node#{i}"
        v.memory = 4096
        v.cpus = 4
      end
      node.vm.provision "shell", path: "bootstrap_node.sh"
    end

  end

end
